RealHoppers:
  Prefix: "&fReal&dHoppers &7>"
  Effects:
    Sounds: true
    Particles: true
  Teleportation-Cooldown: 20
  Drop-Items-If-Full: true
  Material-Values:
    COBBLESTONE: 5
    SAND: 2

Version: 1